### ISSUE TITLE
Parallel arrays in Inventory could be better organised into a single array of items

### ISSUE THREAD

**Issue by pablothedolphin** [TahmidZaman137/Vending-Machine#2]
Define your own custom object that contains the data for one item's name, image reference and price. Then create an array of these so you don't have to manage and access multiple arrays.

**Comment by TahmidZaman137** [comment]
Good idea! Resolved now. Created multiple instances of an "Item" class and put them into a single list. All corresponding code has been edited to accommodate this change.
