### ISSUE TITLE
ReadMe isn't very descriptive

### ISSUE THREAD

**Issue by pablothedolphin** [TahmidZaman137/Vending-Machine#5]
Your readme file could be improved by adding your roadmap in a table form to make it clear what your plans for the future are.

See and example below:

![image](https://user-images.githubusercontent.com/10001744/37278542-fd16af70-25df-11e8-8ce7-82886d033fd2.png)

**Comment by pablothedolphin** [comment]
You can write up a readme file in this web app (left side) and preview how it would look (right side) before committing the change:

https://stackedit.io/app

**Comment by TahmidZaman137** [comment]
Very useful web app. Thanks. Just added a roadmap to the repository as a README.md file.
